// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Lexer.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Lexer {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object lexer=$fix(Lexer.createTransducer());
      $line=7;
      Lexer.testLexer($cast(gold.structures.automaton.ITransducer.class,lexer));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"main",$line);
    }
  }
  public static Object testLexer(ITransducer M) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=13;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=14;
      Object string=null;
      String linea=null;
      linea=$defaultValue(String.class);
      $line=16;
      java.io.BufferedReader sd=null;
      sd=$invokeConstructor(java.io.BufferedReader.class,new Object[]{$invokeConstructor(java.io.InputStreamReader.class,new Object[]{$invokeField(System.class,"in",true,null)})});
      $line=17;
      while (true) {
        if (!($bool(true))) break;
        $line=18;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=19;
        System.out.println($message(new Object[]{"Enter an input string: "}));
        $line=20;
        linea=$cast(String.class,$fix(""));
        $line=21;
        string=$fix("");
        $line=23;
        while (true) {
          if (!($bool(((java.util.Scanner)sc).hasNextLine()))) break;
          $line=24;
          linea=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
          $line=25;
          if ($bool(((java.lang.String)linea).isEmpty())) {
            $line=26;
            break;
          }
          $line=30;
          if ($opEqualY(string,"")) {
            $line=31;
            string=$fix($opAdditY(string,linea));
          }
          else {
            $line=33;
            string=$fix($opAdditY($opAdditY(string,"$"),linea));
          }
        }
        $line=38;
        $invokeMethod("println",$invokeField(System.class,"out",true,null),new Object[]{string});
        $line=39;
        Object result=$fix(((gold.structures.automaton.ITransducer)M).acceptsString($cast(java.lang.String.class,string)));
        $line=40;
        Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
        $line=41;
        System.out.println($message(new Object[]{$opAdditY($opAdditY("The lexer did ",(($bool(result))?(""):("not ")))," accept the string.")}));
        $line=42;
        if ($bool(result)) {
          $line=42;
          System.out.println($message(new Object[]{$opAdditY("Token Stream: ",tokenStream)}));
        }
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"testLexer",$line);
    }
    return $result;
  }
  public static Object names=null;
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=57;
      Object Q=$fix(GCollections.asSet("0","R0","R1","R2","R3","R4","R5","R6","B0","B1","B2","B3","B4","V0","V1","V2","V3","V4","V5","V6","V7","Err","A0","A1","A2","A3","A4","A5","A6","A7","A8","A9","A10","A11","A12","A13","A14","A15","A16","A17","M0","M1","M2","M3","M4","M5","M6","M7","M8","M9","M10","M11","M12","MT0","MT1","MT2","MT3","MT4","MT5","MT6","MT7","OR0","OR1","OR2","OR3","OR4","OL0","OL1","OL2","OL3","OF0","OF1","OF2","OF3","OF4","OB0","OB1","OB2","OB3"));
      $line=70;
      Object \u03A3=$fix($opUnionY($opUnionY($opUnionY($opIntvlY('0','9'),$opIntvlY('a','z')),$opIntvlY('A','Z')),GCollections.asSet(':','_','$','(',')',' ',',')));
      $line=74;
      Object Out=$fix(GCollections.asSet('(',')','R','B','V','v','n','A','t','E','M','0','7','8','9','e','$'));
      $line=78;
      Object q_0=$fix("0");
      $line=81;
      Object F=$fix(GCollections.asSet("0","R6","B4","V3","V5","V6","Err","A7","A9","A14","A16","A17","M5","M6","M7","M11","MT6","OR4","OL3","OF4","OB3"));
      $line=83;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(Lexer.class,"\u03B4"),new GMethod(Lexer.class,"g"),new GMethod(Lexer.class,"h")});
      if (true) break $try;
      $line=84;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=89;
      Object letras=$fix($opUnionY($opIntvlY('a','z'),$opIntvlY('A','Z')));
      $line=90;
      Object digitos=$fix($opIntvlY('0','9'));
      $line=93;
      Object estadosRobot=$fix(GCollections.asSet("R0","R1","R2","R3","R4","R5","R6"));
      $line=94;
      Object estadosBegin=$fix(GCollections.asSet("B0","B1","B2","B3","B4"));
      $line=95;
      Object estadosVars=$fix(GCollections.asSet("V0","V1","V2","V3","V4","V5","V6","V7"));
      $line=96;
      Object estadosAssign=$fix(GCollections.asSet("A0","A1","A2","A3","A4","A5","A6","A7","A8","A9","A10","A11","A12","A13","A14","A15","A16","A17"));
      $line=98;
      Object estadosMove=$fix(GCollections.asSet("M0","M1","M2","M3","M4","M5","M6","M7","M8","M9","M10","M11","M12"));
      $line=100;
      Object estadosMoveToThe=$fix(GCollections.asSet("MT0","MT1","MT2","MT3","MT4","MT5","MT6","MT7"));
      $line=101;
      Object estadosOrientacionRight=$fix(GCollections.asSet("OR0","OR1","OR2","OR3","OR4"));
      $line=102;
      Object estadosOrientacionLeft=$fix(GCollections.asSet("OL0","OL1","OL2","OL3"));
      $line=103;
      Object estadosOrientacionFront=$fix(GCollections.asSet("OF0","OF1","OF2","OF3","OF4"));
      $line=104;
      Object estadosOrientacionBack=$fix(GCollections.asSet("OB0","OB1","OB2","OB3"));
      $line=107;
      if ($bool(($opEqualY(q,"Err")&&$opEqualY(\u03C3,'$')))) {
        $line=107;
        $result="0";
        if (true) break $try;
      }
      else {
        $line=108;
        if ($bool(($opEqualY(q,"Err")&&!$opEqualY(\u03C3,'$')))) {
          $line=108;
          $result="Err";
          if (true) break $try;
        }
        else {
          $line=114;
          if ($bool($opEqualY(q,"0"))) {
            $line=114;
            $result=Lexer.rutinaInicial(q,\u03C3);
            if (true) break $try;
          }
          else {
            $line=117;
            if ($bool($opMembrY(q,estadosRobot))) {
              $line=117;
              $result=Lexer.rutinaRobot(q,\u03C3);
              if (true) break $try;
            }
            else {
              $line=121;
              if ($bool($opMembrY(q,estadosBegin))) {
                $line=121;
                $result=Lexer.rutinaBegin(q,\u03C3);
                if (true) break $try;
              }
              else {
                $line=125;
                if ($bool($opMembrY(q,estadosVars))) {
                  $line=125;
                  $result=Lexer.rutinaVars(q,\u03C3);
                  if (true) break $try;
                }
                else {
                  $line=128;
                  if ($bool($opMembrY(q,estadosAssign))) {
                    $line=128;
                    $result=Lexer.rutinaAssign(q,\u03C3);
                    if (true) break $try;
                  }
                  else {
                    $line=131;
                    if ($bool($opMembrY(q,estadosMove))) {
                      $line=131;
                      $result=Lexer.rutinaMove(q,\u03C3);
                      if (true) break $try;
                    }
                    else {
                      $line=134;
                      if ($bool($opMembrY(q,estadosMoveToThe))) {
                        $line=134;
                        $result=Lexer.rutinaMoveToThe(q,\u03C3);
                        if (true) break $try;
                      }
                      else {
                        $line=137;
                        if ($bool($opMembrY(q,estadosOrientacionRight))) {
                          $line=137;
                          $result=Lexer.rutinaOrientacionRight(q,\u03C3);
                          if (true) break $try;
                        }
                        else {
                          $line=140;
                          if ($bool($opMembrY(q,estadosOrientacionLeft))) {
                            $line=140;
                            $result=Lexer.rutinaOrientacionLeft(q,\u03C3);
                            if (true) break $try;
                          }
                          else {
                            $line=143;
                            if ($bool($opMembrY(q,estadosOrientacionBack))) {
                              $line=143;
                              $result=Lexer.rutinaOrientacionBack(q,\u03C3);
                              if (true) break $try;
                            }
                            else {
                              $line=146;
                              if ($bool($opMembrY(q,estadosOrientacionFront))) {
                                $line=146;
                                $result=Lexer.rutinaOrientacionFront(q,\u03C3);
                                if (true) break $try;
                              }
                              else {
                                $line=149;
                                $result="Err";
                                if (true) break $try;
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=151;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=156;
      String s=null;
      s=$defaultValue(String.class);
      $line=157;
      s=$cast(String.class,$fix(""));
      $line=159;
      if ($opEqualY(q,"Err")) {
        $line=159;
        $result=$opAdditY(s,"$");
        if (true) break $try;
      }
      else {
        $line=160;
        if ($opEqualY(q,"B4")) {
          $line=160;
          $result=$opAdditY(s,"B");
          if (true) break $try;
        }
        else {
          $line=161;
          if ($opEqualY(q,"R6")) {
            $line=161;
            $result=$opAdditY(s,"R");
            if (true) break $try;
          }
          else {
            $line=162;
            if ($opEqualY(q,"V3")) {
              $line=162;
              $result=$opAdditY(s,"V");
              if (true) break $try;
            }
            else {
              $line=163;
              if ($opEqualY(q,"V4")) {
                $line=163;
                $result=$opAdditY(s,"v");
                if (true) break $try;
              }
              else {
                $line=164;
                if ($opEqualY(q,"A7")) {
                  $line=164;
                  $result=$opAdditY(s,"A(");
                  if (true) break $try;
                }
                else {
                  $line=165;
                  if ($opEqualY(q,"A10")) {
                    $line=165;
                    $result=$opAdditY(s,"n");
                    if (true) break $try;
                  }
                  else {
                    $line=166;
                    if ($opEqualY(q,"A14")) {
                      $line=166;
                      $result=$opAdditY(s,"t");
                      if (true) break $try;
                    }
                    else {
                      $line=170;
                      if ($opEqualY(q,"MT6")) {
                        $line=170;
                        $result=$opAdditY(s,"e");
                        if (true) break $try;
                      }
                      else {
                        $line=173;
                        if ($opEqualY(q,"OF4")) {
                          $line=173;
                          $result=$opAdditY(s,"9)");
                          if (true) break $try;
                        }
                        else {
                          $line=174;
                          if ($opEqualY(q,"OB3")) {
                            $line=174;
                            $result=$opAdditY(s,"0)");
                            if (true) break $try;
                          }
                          else {
                            $line=175;
                            if ($opEqualY(q,"OL3")) {
                              $line=175;
                              $result=$opAdditY(s,"8)");
                              if (true) break $try;
                            }
                            else {
                              $line=176;
                              if ($opEqualY(q,"OR4")) {
                                $line=176;
                                $result=$opAdditY(s,"7)");
                                if (true) break $try;
                              }
                              else {
                                $line=181;
                                $result="";
                                if (true) break $try;
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=184;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"g",$line);
    }
    return $result;
  }
  public static Object rutinaInicial(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=188;
      if ($bool(($opEqualY(q,"0")&&$opEqualY(\u03C3,'R')))) {
        $line=188;
        $result="R0";
        if (true) break $try;
      }
      else {
        $line=189;
        if ($bool(($opEqualY(q,"0")&&$opEqualY(\u03C3,'B')))) {
          $line=189;
          $result="B0";
          if (true) break $try;
        }
        else {
          $line=190;
          if ($bool(($opEqualY(q,"0")&&$opEqualY(\u03C3,'V')))) {
            $line=190;
            $result="V0";
            if (true) break $try;
          }
          else {
            $line=192;
            if ($bool(($opEqualY(q,"0")&&$opEqualY(\u03C3,'a')))) {
              $line=192;
              $result="A0";
              if (true) break $try;
            }
            else {
              $line=193;
              if ($bool(($opEqualY(q,"0")&&$opEqualY(\u03C3,'m')))) {
                $line=193;
                $result="M0";
                if (true) break $try;
              }
              else {
                $line=195;
                if ($bool(($opEqualY(q,"0")&&$opEqualY(\u03C3,' ')))) {
                  $line=195;
                  $result="0";
                  if (true) break $try;
                }
                else {
                  $line=196;
                  if ($bool(($opEqualY(q,"0")&&$opEqualY(\u03C3,'$')))) {
                    $line=196;
                    $result="0";
                    if (true) break $try;
                  }
                  else {
                    $line=197;
                    $result="Err";
                    if (true) break $try;
                  }
                }
              }
            }
          }
        }
      }
      $line=200;
      $rethrow(new RuntimeException("The function \"rutinaInicial(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaInicial",$line);
    }
    return $result;
  }
  public static Object rutinaRobot(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=205;
      if ($bool(($opEqualY(q,"R0")&&$opEqualY(\u03C3,'O')))) {
        $line=205;
        $result="R1";
        if (true) break $try;
      }
      else {
        $line=206;
        if ($bool(($opEqualY(q,"R1")&&$opEqualY(\u03C3,'B')))) {
          $line=206;
          $result="R2";
          if (true) break $try;
        }
        else {
          $line=207;
          if ($bool(($opEqualY(q,"R2")&&$opEqualY(\u03C3,'O')))) {
            $line=207;
            $result="R3";
            if (true) break $try;
          }
          else {
            $line=208;
            if ($bool(($opEqualY(q,"R3")&&$opEqualY(\u03C3,'T')))) {
              $line=208;
              $result="R4";
              if (true) break $try;
            }
            else {
              $line=209;
              if ($bool(($opEqualY(q,"R4")&&$opEqualY(\u03C3,'_')))) {
                $line=209;
                $result="R5";
                if (true) break $try;
              }
              else {
                $line=210;
                if ($bool(($opEqualY(q,"R5")&&$opEqualY(\u03C3,'R')))) {
                  $line=210;
                  $result="R6";
                  if (true) break $try;
                }
                else {
                  $line=211;
                  if ($bool(($opEqualY(q,"R6")&&$opEqualY(\u03C3,'$')))) {
                    $line=211;
                    $result="0";
                    if (true) break $try;
                  }
                  else {
                    $line=212;
                    $result="Err";
                    if (true) break $try;
                  }
                }
              }
            }
          }
        }
      }
      $line=215;
      $rethrow(new RuntimeException("The function \"rutinaRobot(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaRobot",$line);
    }
    return $result;
  }
  public static Object rutinaBegin(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=220;
      if ($bool(($opEqualY(q,"B0")&&$opEqualY(\u03C3,'E')))) {
        $line=220;
        $result="B1";
        if (true) break $try;
      }
      else {
        $line=221;
        if ($bool(($opEqualY(q,"B1")&&$opEqualY(\u03C3,'G')))) {
          $line=221;
          $result="B2";
          if (true) break $try;
        }
        else {
          $line=222;
          if ($bool(($opEqualY(q,"B2")&&$opEqualY(\u03C3,'I')))) {
            $line=222;
            $result="B3";
            if (true) break $try;
          }
          else {
            $line=223;
            if ($bool(($opEqualY(q,"B3")&&$opEqualY(\u03C3,'N')))) {
              $line=223;
              $result="B4";
              if (true) break $try;
            }
            else {
              $line=224;
              if ($bool(($opEqualY(q,"B4")&&$opEqualY(\u03C3,'$')))) {
                $line=224;
                $result="0";
                if (true) break $try;
              }
              else {
                $line=226;
                $result="Err";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=229;
      $rethrow(new RuntimeException("The function \"rutinaBegin(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaBegin",$line);
    }
    return $result;
  }
  public static Object rutinaVars(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=234;
      Object letras=$fix($opUnionY($opIntvlY('a','z'),$opIntvlY('A','Z')));
      $line=235;
      Object digitos=$fix($opIntvlY('0','9'));
      $line=237;
      if ($bool(($opEqualY(q,"V0")&&$opEqualY(\u03C3,'A')))) {
        $line=237;
        $result="V1";
        if (true) break $try;
      }
      else {
        $line=238;
        if ($bool(($opEqualY(q,"V1")&&$opEqualY(\u03C3,'R')))) {
          $line=238;
          $result="V2";
          if (true) break $try;
        }
        else {
          $line=239;
          if ($bool(($opEqualY(q,"V2")&&$opEqualY(\u03C3,'S')))) {
            $line=239;
            $result="V3";
            if (true) break $try;
          }
          else {
            $line=240;
            if ($bool(($opEqualY(q,"V3")&&$opEqualY(\u03C3,' ')))) {
              $line=240;
              $result="V4";
              if (true) break $try;
            }
            else {
              $line=241;
              if ($bool(($opEqualY(q,"V3")&&$opEqualY(\u03C3,'$')))) {
                $line=241;
                $result="0";
                if (true) break $try;
              }
              else {
                $line=242;
                if ($bool(($opEqualY(q,"V4")&&$opMembrY(\u03C3,letras)))) {
                  $line=242;
                  $result="V5";
                  if (true) break $try;
                }
                else {
                  $line=243;
                  if ($bool(($opEqualY(q,"V5")&&$opMembrY(\u03C3,letras)))) {
                    $line=243;
                    $result="V5";
                    if (true) break $try;
                  }
                  else {
                    $line=244;
                    if ($bool(($opEqualY(q,"V5")&&$opMembrY(\u03C3,$opUnionY(digitos,GCollections.asSet('_')))))) {
                      $line=244;
                      $result="V6";
                      if (true) break $try;
                    }
                    else {
                      $line=245;
                      if ($bool(($opEqualY(q,"V5")&&$opEqualY(\u03C3,',')))) {
                        $line=245;
                        $result="V7";
                        if (true) break $try;
                      }
                      else {
                        $line=246;
                        if ($bool(($opEqualY(q,"V5")&&$opEqualY(\u03C3,'$')))) {
                          $line=246;
                          $result="0";
                          if (true) break $try;
                        }
                        else {
                          $line=247;
                          if ($bool(($opEqualY(q,"V6")&&$opMembrY(\u03C3,$opUnionY(digitos,letras))))) {
                            $line=247;
                            $result="V6";
                            if (true) break $try;
                          }
                          else {
                            $line=248;
                            if ($bool(($opEqualY(q,"V6")&&$opEqualY(\u03C3,',')))) {
                              $line=248;
                              $result="V7";
                              if (true) break $try;
                            }
                            else {
                              $line=249;
                              if ($bool(($opEqualY(q,"V6")&&$opEqualY(\u03C3,'$')))) {
                                $line=249;
                                $result="0";
                                if (true) break $try;
                              }
                              else {
                                $line=250;
                                if ($bool(($opEqualY(q,"V7")&&$opMembrY(\u03C3,letras)))) {
                                  $line=250;
                                  $result="V5";
                                  if (true) break $try;
                                }
                                else {
                                  $line=251;
                                  if ($bool(($opEqualY(q,"V7")&&$opEqualY(\u03C3,' ')))) {
                                    $line=251;
                                    $result="V4";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=253;
                                    $result="Err";
                                    if (true) break $try;
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=256;
      $rethrow(new RuntimeException("The function \"rutinaVars(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaVars",$line);
    }
    return $result;
  }
  public static Object rutinaAssign(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=262;
      Object letras=$fix($opUnionY($opIntvlY('a','z'),$opIntvlY('A','Z')));
      $line=263;
      Object digitos=$fix($opIntvlY('0','9'));
      $line=266;
      if ($bool(($opEqualY(q,"A0")&&$opEqualY(\u03C3,'s')))) {
        $line=266;
        $result="A1";
        if (true) break $try;
      }
      else {
        $line=267;
        if ($bool(($opEqualY(q,"A1")&&$opEqualY(\u03C3,'s')))) {
          $line=267;
          $result="A2";
          if (true) break $try;
        }
        else {
          $line=268;
          if ($bool(($opEqualY(q,"A2")&&$opEqualY(\u03C3,'i')))) {
            $line=268;
            $result="A3";
            if (true) break $try;
          }
          else {
            $line=269;
            if ($bool(($opEqualY(q,"A3")&&$opEqualY(\u03C3,'g')))) {
              $line=269;
              $result="A4";
              if (true) break $try;
            }
            else {
              $line=270;
              if ($bool(($opEqualY(q,"A4")&&$opEqualY(\u03C3,'n')))) {
                $line=270;
                $result="A5";
                if (true) break $try;
              }
              else {
                $line=273;
                if ($bool(($opEqualY(q,"A5")&&$opEqualY(\u03C3,' ')))) {
                  $line=273;
                  $result="A6";
                  if (true) break $try;
                }
                else {
                  $line=274;
                  if ($bool(($opEqualY(q,"A5")&&$opEqualY(\u03C3,':')))) {
                    $line=274;
                    $result="A7";
                    if (true) break $try;
                  }
                  else {
                    $line=277;
                    if ($bool(($opEqualY(q,"A6")&&$opEqualY(\u03C3,':')))) {
                      $line=277;
                      $result="A7";
                      if (true) break $try;
                    }
                    else {
                      $line=278;
                      if ($bool(($opEqualY(q,"A7")&&$opEqualY(\u03C3,'$')))) {
                        $line=278;
                        $result="0";
                        if (true) break $try;
                      }
                      else {
                        $line=281;
                        if ($bool(($opEqualY(q,"A7")&&$opEqualY(\u03C3,' ')))) {
                          $line=281;
                          $result="A8";
                          if (true) break $try;
                        }
                        else {
                          $line=282;
                          if ($bool(($opEqualY(q,"A7")&&$opMembrY(\u03C3,digitos)))) {
                            $line=282;
                            $result="A9";
                            if (true) break $try;
                          }
                          else {
                            $line=283;
                            if ($bool(($opEqualY(q,"A8")&&$opMembrY(\u03C3,digitos)))) {
                              $line=283;
                              $result="A9";
                              if (true) break $try;
                            }
                            else {
                              $line=286;
                              if ($bool(($opEqualY(q,"A9")&&$opMembrY(\u03C3,digitos)))) {
                                $line=286;
                                $result="A9";
                                if (true) break $try;
                              }
                              else {
                                $line=287;
                                if ($bool(($opEqualY(q,"A9")&&$opEqualY(\u03C3,'$')))) {
                                  $line=287;
                                  $result="0";
                                  if (true) break $try;
                                }
                                else {
                                  $line=288;
                                  if ($bool(($opEqualY(q,"A9")&&$opEqualY(\u03C3,' ')))) {
                                    $line=288;
                                    $result="A10";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=291;
                                    if ($bool(($opEqualY(q,"A10")&&$opEqualY(\u03C3,'t')))) {
                                      $line=291;
                                      $result="A11";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=292;
                                      if ($bool(($opEqualY(q,"A11")&&$opEqualY(\u03C3,'o')))) {
                                        $line=292;
                                        $result="A12";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=295;
                                        if ($bool(($opEqualY(q,"A12")&&$opEqualY(\u03C3,' ')))) {
                                          $line=295;
                                          $result="A13";
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=296;
                                          if ($bool(($opEqualY(q,"A12")&&$opEqualY(\u03C3,':')))) {
                                            $line=296;
                                            $result="A14";
                                            if (true) break $try;
                                          }
                                          else {
                                            $line=297;
                                            if ($bool(($opEqualY(q,"A13")&&$opEqualY(\u03C3,':')))) {
                                              $line=297;
                                              $result="A14";
                                              if (true) break $try;
                                            }
                                            else {
                                              $line=300;
                                              if ($bool(($opEqualY(q,"A14")&&$opEqualY(\u03C3,'$')))) {
                                                $line=300;
                                                $result="0";
                                                if (true) break $try;
                                              }
                                              else {
                                                $line=301;
                                                if ($bool(($opEqualY(q,"A14")&&$opEqualY(\u03C3,' ')))) {
                                                  $line=301;
                                                  $result="A15";
                                                  if (true) break $try;
                                                }
                                                else {
                                                  $line=302;
                                                  if ($bool(($opEqualY(q,"A14")&&$opMembrY(\u03C3,letras)))) {
                                                    $line=302;
                                                    $result="A16";
                                                    if (true) break $try;
                                                  }
                                                  else {
                                                    $line=303;
                                                    if ($bool(($opEqualY(q,"A15")&&$opMembrY(\u03C3,letras)))) {
                                                      $line=303;
                                                      $result="A16";
                                                      if (true) break $try;
                                                    }
                                                    else {
                                                      $line=306;
                                                      if ($bool(($opEqualY(q,"A16")&&$opEqualY(\u03C3,'$')))) {
                                                        $line=306;
                                                        $result="0";
                                                        if (true) break $try;
                                                      }
                                                      else {
                                                        $line=307;
                                                        if ($bool(($opEqualY(q,"A16")&&$opMembrY(\u03C3,letras)))) {
                                                          $line=307;
                                                          $result="A16";
                                                          if (true) break $try;
                                                        }
                                                        else {
                                                          $line=310;
                                                          if ($bool(($opEqualY(q,"A16")&&$opMembrY(\u03C3,digitos)))) {
                                                            $line=310;
                                                            $result="A17";
                                                            if (true) break $try;
                                                          }
                                                          else {
                                                            $line=311;
                                                            if ($bool(($opEqualY(q,"A16")&&$opEqualY(\u03C3,'_')))) {
                                                              $line=311;
                                                              $result="A17";
                                                              if (true) break $try;
                                                            }
                                                            else {
                                                              $line=314;
                                                              if ($bool(($opEqualY(q,"A17")&&$opMembrY(\u03C3,$opUnionY(digitos,letras))))) {
                                                                $line=314;
                                                                $result="A17";
                                                                if (true) break $try;
                                                              }
                                                              else {
                                                                $line=317;
                                                                if ($bool(($opEqualY(q,"A17")&&$opEqualY(\u03C3,'$')))) {
                                                                  $line=317;
                                                                  $result="0";
                                                                  if (true) break $try;
                                                                }
                                                                else {
                                                                  $line=320;
                                                                  $result="Err";
                                                                  if (true) break $try;
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=322;
      $rethrow(new RuntimeException("The function \"rutinaAssign(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaAssign",$line);
    }
    return $result;
  }
  public static Object rutinaMove(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=328;
      Object letras=$fix($opUnionY($opIntvlY('a','z'),$opIntvlY('A','Z')));
      $line=329;
      Object digitos=$fix($opIntvlY('0','9'));
      $line=332;
      if ($bool(($opEqualY(q,"M0")&&$opEqualY(\u03C3,'o')))) {
        $line=332;
        $result="M1";
        if (true) break $try;
      }
      else {
        $line=333;
        if ($bool(($opEqualY(q,"M1")&&$opEqualY(\u03C3,'v')))) {
          $line=333;
          $result="M2";
          if (true) break $try;
        }
        else {
          $line=334;
          if ($bool(($opEqualY(q,"M2")&&$opEqualY(\u03C3,'e')))) {
            $line=334;
            $result="M3";
            if (true) break $try;
          }
          else {
            $line=337;
            if ($bool(($opEqualY(q,"M3")&&$opEqualY(\u03C3,' ')))) {
              $line=337;
              $result="M4";
              if (true) break $try;
            }
            else {
              $line=338;
              if ($bool(($opEqualY(q,"M3")&&$opEqualY(\u03C3,':')))) {
                $line=338;
                $result="M5";
                if (true) break $try;
              }
              else {
                $line=341;
                if ($bool(($opEqualY(q,"M4")&&$opEqualY(\u03C3,':')))) {
                  $line=341;
                  $result="M5";
                  if (true) break $try;
                }
                else {
                  $line=342;
                  if ($bool(($opEqualY(q,"M5")&&$opEqualY(\u03C3,'$')))) {
                    $line=342;
                    $result="0";
                    if (true) break $try;
                  }
                  else {
                    $line=345;
                    if ($bool(($opEqualY(q,"M5")&&$opEqualY(\u03C3,' ')))) {
                      $line=345;
                      $result="M8";
                      if (true) break $try;
                    }
                    else {
                      $line=346;
                      if ($bool(($opEqualY(q,"M5")&&$opMembrY(\u03C3,letras)))) {
                        $line=346;
                        $result="M6";
                        if (true) break $try;
                      }
                      else {
                        $line=347;
                        if ($bool(($opEqualY(q,"M8")&&$opMembrY(\u03C3,letras)))) {
                          $line=347;
                          $result="M6";
                          if (true) break $try;
                        }
                        else {
                          $line=348;
                          if ($bool(($opEqualY(q,"M6")&&$opMembrY(\u03C3,letras)))) {
                            $line=348;
                            $result="M6";
                            if (true) break $try;
                          }
                          else {
                            $line=349;
                            if ($bool(($opEqualY(q,"M6")&&$opMembrY(\u03C3,digitos)))) {
                              $line=349;
                              $result="M7";
                              if (true) break $try;
                            }
                            else {
                              $line=350;
                              if ($bool(($opEqualY(q,"M6")&&$opEqualY(\u03C3,'_')))) {
                                $line=350;
                                $result="M7";
                                if (true) break $try;
                              }
                              else {
                                $line=351;
                                if ($bool(($opEqualY(q,"M6")&&$opEqualY(\u03C3,'$')))) {
                                  $line=351;
                                  $result="0";
                                  if (true) break $try;
                                }
                                else {
                                  $line=353;
                                  if ($bool(($opEqualY(q,"M7")&&$opMembrY(\u03C3,digitos)))) {
                                    $line=353;
                                    $result="M7";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=354;
                                    if ($bool(($opEqualY(q,"M7")&&$opMembrY(\u03C3,letras)))) {
                                      $line=354;
                                      $result="M7";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=355;
                                      if ($bool(($opEqualY(q,"M7")&&$opEqualY(\u03C3,'$')))) {
                                        $line=355;
                                        $result="0";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=356;
                                        if ($bool(($opEqualY(q,"M7")&&$opEqualY(\u03C3,' ')))) {
                                          $line=356;
                                          $result="M12";
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=359;
                                          if ($bool(($opEqualY(q,"M5")&&$opMembrY(\u03C3,digitos)))) {
                                            $line=359;
                                            $result="M11";
                                            if (true) break $try;
                                          }
                                          else {
                                            $line=360;
                                            if ($bool(($opEqualY(q,"M8")&&$opMembrY(\u03C3,digitos)))) {
                                              $line=360;
                                              $result="M11";
                                              if (true) break $try;
                                            }
                                            else {
                                              $line=361;
                                              if ($bool(($opEqualY(q,"M11")&&$opMembrY(\u03C3,digitos)))) {
                                                $line=361;
                                                $result="M11";
                                                if (true) break $try;
                                              }
                                              else {
                                                $line=362;
                                                if ($bool(($opEqualY(q,"M11")&&$opEqualY(\u03C3,'$')))) {
                                                  $line=362;
                                                  $result="0";
                                                  if (true) break $try;
                                                }
                                                else {
                                                  $line=363;
                                                  if ($bool(($opEqualY(q,"M11")&&$opEqualY(\u03C3,' ')))) {
                                                    $line=363;
                                                    $result="M12";
                                                    if (true) break $try;
                                                  }
                                                  else {
                                                    $line=366;
                                                    if ($bool(($opEqualY(q,"M12")&&$opEqualY(\u03C3,'t')))) {
                                                      $line=366;
                                                      $result="MT0";
                                                      if (true) break $try;
                                                    }
                                                    else {
                                                      $line=370;
                                                      $result="Err";
                                                      if (true) break $try;
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=372;
      $rethrow(new RuntimeException("The function \"rutinaMove(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaMove",$line);
    }
    return $result;
  }
  public static Object rutinaMoveToThe(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=378;
      Object letras=$fix($opUnionY($opIntvlY('a','z'),$opIntvlY('A','Z')));
      $line=379;
      Object digitos=$fix($opIntvlY('0','9'));
      $line=382;
      if ($bool(($opEqualY(q,"MT0")&&$opEqualY(\u03C3,'o')))) {
        $line=382;
        $result="MT1";
        if (true) break $try;
      }
      else {
        $line=383;
        if ($bool(($opEqualY(q,"MT1")&&$opEqualY(\u03C3,'T')))) {
          $line=383;
          $result="MT2";
          if (true) break $try;
        }
        else {
          $line=384;
          if ($bool(($opEqualY(q,"MT2")&&$opEqualY(\u03C3,'h')))) {
            $line=384;
            $result="MT3";
            if (true) break $try;
          }
          else {
            $line=385;
            if ($bool(($opEqualY(q,"MT3")&&$opEqualY(\u03C3,'e')))) {
              $line=385;
              $result="MT4";
              if (true) break $try;
            }
            else {
              $line=386;
              if ($bool(($opEqualY(q,"MT4")&&$opEqualY(\u03C3,' ')))) {
                $line=386;
                $result="MT5";
                if (true) break $try;
              }
              else {
                $line=387;
                if ($bool(($opEqualY(q,"MT4")&&$opEqualY(\u03C3,':')))) {
                  $line=387;
                  $result="MT6";
                  if (true) break $try;
                }
                else {
                  $line=388;
                  if ($bool(($opEqualY(q,"MT5")&&$opEqualY(\u03C3,':')))) {
                    $line=388;
                    $result="MT6";
                    if (true) break $try;
                  }
                  else {
                    $line=389;
                    if ($bool(($opEqualY(q,"MT6")&&$opEqualY(\u03C3,' ')))) {
                      $line=389;
                      $result="MT7";
                      if (true) break $try;
                    }
                    else {
                      $line=392;
                      if ($bool(($opEqualY(q,"MT6")&&$opEqualY(\u03C3,'r')))) {
                        $line=392;
                        $result="OR0";
                        if (true) break $try;
                      }
                      else {
                        $line=393;
                        if ($bool(($opEqualY(q,"MT6")&&$opEqualY(\u03C3,'l')))) {
                          $line=393;
                          $result="OL0";
                          if (true) break $try;
                        }
                        else {
                          $line=394;
                          if ($bool(($opEqualY(q,"MT6")&&$opEqualY(\u03C3,'f')))) {
                            $line=394;
                            $result="OF0";
                            if (true) break $try;
                          }
                          else {
                            $line=395;
                            if ($bool(($opEqualY(q,"MT6")&&$opEqualY(\u03C3,'b')))) {
                              $line=395;
                              $result="OB0";
                              if (true) break $try;
                            }
                            else {
                              $line=396;
                              if ($bool(($opEqualY(q,"MT6")&&$opEqualY(\u03C3,'$')))) {
                                $line=396;
                                $result="0";
                                if (true) break $try;
                              }
                              else {
                                $line=399;
                                if ($bool(($opEqualY(q,"MT7")&&$opEqualY(\u03C3,'r')))) {
                                  $line=399;
                                  $result="OR0";
                                  if (true) break $try;
                                }
                                else {
                                  $line=400;
                                  if ($bool(($opEqualY(q,"MT7")&&$opEqualY(\u03C3,'l')))) {
                                    $line=400;
                                    $result="OL0";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=401;
                                    if ($bool(($opEqualY(q,"MT7")&&$opEqualY(\u03C3,'f')))) {
                                      $line=401;
                                      $result="OF0";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=402;
                                      if ($bool(($opEqualY(q,"MT7")&&$opEqualY(\u03C3,'b')))) {
                                        $line=402;
                                        $result="OB0";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=403;
                                        if ($bool(($opEqualY(q,"MT7")&&$opEqualY(\u03C3,'$')))) {
                                          $line=403;
                                          $result="0";
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=407;
                                          $result="Err";
                                          if (true) break $try;
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=409;
      $rethrow(new RuntimeException("The function \"rutinaMoveToThe(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaMoveToThe",$line);
    }
    return $result;
  }
  public static Object rutinaOrientacionRight(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=415;
      if ($bool(($opEqualY(q,"OR0")&&$opEqualY(\u03C3,'i')))) {
        $line=415;
        $result="OR1";
        if (true) break $try;
      }
      else {
        $line=416;
        if ($bool(($opEqualY(q,"OR1")&&$opEqualY(\u03C3,'g')))) {
          $line=416;
          $result="OR2";
          if (true) break $try;
        }
        else {
          $line=417;
          if ($bool(($opEqualY(q,"OR2")&&$opEqualY(\u03C3,'h')))) {
            $line=417;
            $result="OR3";
            if (true) break $try;
          }
          else {
            $line=418;
            if ($bool(($opEqualY(q,"OR3")&&$opEqualY(\u03C3,'t')))) {
              $line=418;
              $result="OR4";
              if (true) break $try;
            }
            else {
              $line=419;
              if ($bool(($opEqualY(q,"OR4")&&$opEqualY(\u03C3,'$')))) {
                $line=419;
                $result="0";
                if (true) break $try;
              }
              else {
                $line=423;
                $result="Err";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=425;
      $rethrow(new RuntimeException("The function \"rutinaOrientacionRight(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaOrientacionRight",$line);
    }
    return $result;
  }
  public static Object rutinaOrientacionFront(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=432;
      if ($bool(($opEqualY(q,"OF0")&&$opEqualY(\u03C3,'r')))) {
        $line=432;
        $result="OF1";
        if (true) break $try;
      }
      else {
        $line=433;
        if ($bool(($opEqualY(q,"OF1")&&$opEqualY(\u03C3,'o')))) {
          $line=433;
          $result="OF2";
          if (true) break $try;
        }
        else {
          $line=434;
          if ($bool(($opEqualY(q,"OF2")&&$opEqualY(\u03C3,'n')))) {
            $line=434;
            $result="OF3";
            if (true) break $try;
          }
          else {
            $line=435;
            if ($bool(($opEqualY(q,"OF3")&&$opEqualY(\u03C3,'t')))) {
              $line=435;
              $result="OF4";
              if (true) break $try;
            }
            else {
              $line=436;
              if ($bool(($opEqualY(q,"OF4")&&$opEqualY(\u03C3,'$')))) {
                $line=436;
                $result="0";
                if (true) break $try;
              }
              else {
                $line=440;
                $result="Err";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=442;
      $rethrow(new RuntimeException("The function \"rutinaOrientacionFront(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaOrientacionFront",$line);
    }
    return $result;
  }
  public static Object rutinaOrientacionBack(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=449;
      if ($bool(($opEqualY(q,"OB0")&&$opEqualY(\u03C3,'a')))) {
        $line=449;
        $result="OB1";
        if (true) break $try;
      }
      else {
        $line=450;
        if ($bool(($opEqualY(q,"OB1")&&$opEqualY(\u03C3,'c')))) {
          $line=450;
          $result="OB2";
          if (true) break $try;
        }
        else {
          $line=451;
          if ($bool(($opEqualY(q,"OB2")&&$opEqualY(\u03C3,'k')))) {
            $line=451;
            $result="OB3";
            if (true) break $try;
          }
          else {
            $line=452;
            if ($bool(($opEqualY(q,"OB3")&&$opEqualY(\u03C3,'$')))) {
              $line=452;
              $result="0";
              if (true) break $try;
            }
            else {
              $line=456;
              $result="Err";
              if (true) break $try;
            }
          }
        }
      }
      $line=458;
      $rethrow(new RuntimeException("The function \"rutinaOrientacionBack(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaOrientacionBack",$line);
    }
    return $result;
  }
  public static Object rutinaOrientacionLeft(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=464;
      if ($bool(($opEqualY(q,"OL0")&&$opEqualY(\u03C3,'e')))) {
        $line=464;
        $result="OL1";
        if (true) break $try;
      }
      else {
        $line=465;
        if ($bool(($opEqualY(q,"OL1")&&$opEqualY(\u03C3,'f')))) {
          $line=465;
          $result="OL2";
          if (true) break $try;
        }
        else {
          $line=466;
          if ($bool(($opEqualY(q,"OL2")&&$opEqualY(\u03C3,'t')))) {
            $line=466;
            $result="OL3";
            if (true) break $try;
          }
          else {
            $line=467;
            if ($bool(($opEqualY(q,"OL3")&&$opEqualY(\u03C3,'$')))) {
              $line=467;
              $result="0";
              if (true) break $try;
            }
            else {
              $line=471;
              $result="Err";
              if (true) break $try;
            }
          }
        }
      }
      $line=473;
      $rethrow(new RuntimeException("The function \"rutinaOrientacionLeft(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"rutinaOrientacionLeft",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=475;
      String s=null;
      s=$defaultValue(String.class);
      $line=476;
      s=$cast(String.class,$fix(""));
      $line=477;
      Object letras=$fix($opUnionY($opIntvlY('a','z'),$opIntvlY('A','Z')));
      $line=478;
      Object digitos=$fix($opIntvlY('0','9'));
      $line=480;
      if (($opEqualY(q,"A14")&&$opMembrY(\u03C3,letras))) {
        $line=480;
        $result=$opAdditY(s,"v)");
        if (true) break $try;
      }
      else {
        $line=481;
        if (($opEqualY(q,"A15")&&$opMembrY(\u03C3,letras))) {
          $line=481;
          $result=$opAdditY(s,"v)");
          if (true) break $try;
        }
        else {
          $line=484;
          if (($opEqualY(q,"M3")&&$opEqualY(\u03C3,':'))) {
            $line=484;
            $result=$opAdditY(s,"M(");
            if (true) break $try;
          }
          else {
            $line=485;
            if (($opEqualY(q,"M4")&&$opEqualY(\u03C3,':'))) {
              $line=485;
              $result=$opAdditY(s,"M(");
              if (true) break $try;
            }
            else {
              $line=486;
              if (($opEqualY(q,"M5")&&$opMembrY(\u03C3,letras))) {
                $line=486;
                $result=$opAdditY(s,"v)");
                if (true) break $try;
              }
              else {
                $line=487;
                if (($opEqualY(q,"M8")&&$opMembrY(\u03C3,letras))) {
                  $line=487;
                  $result=$opAdditY(s,"v)");
                  if (true) break $try;
                }
                else {
                  $line=488;
                  if (($opEqualY(q,"M8")&&$opMembrY(\u03C3,digitos))) {
                    $line=488;
                    $result=$opAdditY(s,"n)");
                    if (true) break $try;
                  }
                  else {
                    $line=489;
                    if (($opEqualY(q,"M5")&&$opMembrY(\u03C3,digitos))) {
                      $line=489;
                      $result=$opAdditY(s,"n)");
                      if (true) break $try;
                    }
                    else {
                      $line=491;
                      $result="";
                      if (true) break $try;
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=493;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"h",$line);
    }
    return $result;
  }
}
