// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Lexer.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Lexer {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object lexer=$fix(Lexer.createTransducer());
      $line=7;
      Lexer.testLexer($cast(gold.structures.automaton.ITransducer.class,lexer));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"main",$line);
    }
  }
  public static Object testLexer(ITransducer M) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=13;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=14;
      Object string=null;
      String linea=null;
      linea=$defaultValue(String.class);
      $line=16;
      java.io.BufferedReader sd=null;
      sd=$invokeConstructor(java.io.BufferedReader.class,new Object[]{$invokeConstructor(java.io.InputStreamReader.class,new Object[]{$invokeField(System.class,"in",true,null)})});
      $line=17;
      while (true) {
        if (!($bool(true))) break;
        $line=18;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=19;
        System.out.println($message(new Object[]{"Enter an input string: "}));
        $line=20;
        linea=$cast(String.class,$fix(""));
        $line=21;
        string=$fix("");
        $line=23;
        while (true) {
          if (!($bool(((java.util.Scanner)sc).hasNextLine()))) break;
          $line=24;
          linea=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
          $line=25;
          if ($bool(((java.lang.String)linea).isEmpty())) {
            $line=26;
            break;
          }
          $line=30;
          if ($opEqualY(string,"")) {
            $line=31;
            string=$fix($opAdditY(string,linea));
          }
          else {
            $line=33;
            string=$fix($opAdditY($opAdditY(string,"$"),linea));
          }
        }
        $line=38;
        $invokeMethod("println",$invokeField(System.class,"out",true,null),new Object[]{string});
        $line=39;
        Object result=$fix(((gold.structures.automaton.ITransducer)M).acceptsString($cast(java.lang.String.class,string)));
        $line=40;
        Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
        $line=41;
        System.out.println($message(new Object[]{$opAdditY($opAdditY("The lexer did ",(($bool(result))?(""):("not ")))," accept the string.")}));
        $line=42;
        if ($bool(result)) {
          $line=42;
          System.out.println($message(new Object[]{$opAdditY("Token Stream: ",tokenStream)}));
        }
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"testLexer",$line);
    }
    return $result;
  }
  public static Object names=null;
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=56;
      Object preKW=$fix(GCollections.asSet("p","pl","plu","plus","t","ti","tim","time","times"));
      $line=57;
      Object Q=$fix(GCollections.asSet("0","1","2","R1","R2","R3","R4","R5","R6","R7","1A","B0","B1","B2","B3","B4","V0","V1","V2","V3","V4","V5","V6","V7","Err","E0","E1","E2","A0","A1","A2","A3","A4","A5","A6","A7","A8","A9","A10","A11","A12","A13","A14","A15","A16","A17"));
      $line=64;
      Object \u03A3=$fix($opUnionY($opUnionY($opUnionY($opIntvlY('0','9'),$opIntvlY('a','z')),$opIntvlY('A','Z')),GCollections.asSet(':','_','$','(',')',' ',',')));
      $line=68;
      Object Out=$fix(GCollections.asSet('(',')','R','B','V','v','n','A','t','E'));
      $line=71;
      Object q_0=$fix("0");
      $line=72;
      Object F=$fix(GCollections.asSet("E2"));
      $line=73;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(Lexer.class,"\u03B4"),new GMethod(Lexer.class,"g"),new GMethod(Lexer.class,"h")});
      if (true) break $try;
      $line=74;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=79;
      Object letras=$fix($opUnionY($opIntvlY('a','z'),$opIntvlY('A','Z')));
      $line=80;
      Object digitos=$fix($opIntvlY('0','9'));
      $line=82;
      if ($bool($opEqualY(q,"Err"))) {
        $line=82;
        $result="Err";
        if (true) break $try;
      }
      else {
        $line=83;
        if ($bool(($opEqualY(q,"0")&&$opEqualY(\u03C3,'R')))) {
          $line=83;
          $result="R1";
          if (true) break $try;
        }
        else {
          $line=84;
          if ($bool(($opEqualY(q,"R1")&&$opEqualY(\u03C3,'O')))) {
            $line=84;
            $result="R2";
            if (true) break $try;
          }
          else {
            $line=85;
            if ($bool(($opEqualY(q,"R2")&&$opEqualY(\u03C3,'B')))) {
              $line=85;
              $result="R3";
              if (true) break $try;
            }
            else {
              $line=86;
              if ($bool(($opEqualY(q,"R3")&&$opEqualY(\u03C3,'O')))) {
                $line=86;
                $result="R4";
                if (true) break $try;
              }
              else {
                $line=87;
                if ($bool(($opEqualY(q,"R4")&&$opEqualY(\u03C3,'T')))) {
                  $line=87;
                  $result="R5";
                  if (true) break $try;
                }
                else {
                  $line=88;
                  if ($bool(($opEqualY(q,"R5")&&$opEqualY(\u03C3,'_')))) {
                    $line=88;
                    $result="R6";
                    if (true) break $try;
                  }
                  else {
                    $line=89;
                    if ($bool(($opEqualY(q,"R6")&&$opEqualY(\u03C3,'R')))) {
                      $line=89;
                      $result="R7";
                      if (true) break $try;
                    }
                    else {
                      $line=90;
                      if ($bool(($opEqualY(q,"R7")&&$opEqualY(\u03C3,'$')))) {
                        $line=90;
                        $result="1";
                        if (true) break $try;
                      }
                      else {
                        $line=91;
                        if ($bool(($opEqualY(q,"1")&&$opEqualY(\u03C3,'B')))) {
                          $line=91;
                          $result="B0";
                          if (true) break $try;
                        }
                        else {
                          $line=92;
                          if ($bool(($opEqualY(q,"1")&&$opEqualY(\u03C3,'V')))) {
                            $line=92;
                            $result="V0";
                            if (true) break $try;
                          }
                          else {
                            $line=93;
                            if ($bool(($opEqualY(q,"B0")&&$opEqualY(\u03C3,'E')))) {
                              $line=93;
                              $result="B1";
                              if (true) break $try;
                            }
                            else {
                              $line=94;
                              if ($bool(($opEqualY(q,"B1")&&$opEqualY(\u03C3,'G')))) {
                                $line=94;
                                $result="B2";
                                if (true) break $try;
                              }
                              else {
                                $line=95;
                                if ($bool(($opEqualY(q,"B2")&&$opEqualY(\u03C3,'I')))) {
                                  $line=95;
                                  $result="B3";
                                  if (true) break $try;
                                }
                                else {
                                  $line=96;
                                  if ($bool(($opEqualY(q,"B3")&&$opEqualY(\u03C3,'N')))) {
                                    $line=96;
                                    $result="B4";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=97;
                                    if ($bool(($opEqualY(q,"V0")&&$opEqualY(\u03C3,'A')))) {
                                      $line=97;
                                      $result="V1";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=98;
                                      if ($bool(($opEqualY(q,"V1")&&$opEqualY(\u03C3,'R')))) {
                                        $line=98;
                                        $result="V2";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=99;
                                        if ($bool(($opEqualY(q,"V2")&&$opEqualY(\u03C3,'S')))) {
                                          $line=99;
                                          $result="V3";
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=100;
                                          if ($bool(($opEqualY(q,"V3")&&$opEqualY(\u03C3,' ')))) {
                                            $line=100;
                                            $result="V4";
                                            if (true) break $try;
                                          }
                                          else {
                                            $line=101;
                                            if ($bool(($opEqualY(q,"V4")&&$opMembrY(\u03C3,letras)))) {
                                              $line=101;
                                              $result="V5";
                                              if (true) break $try;
                                            }
                                            else {
                                              $line=102;
                                              if ($bool(($opEqualY(q,"V5")&&$opMembrY(\u03C3,letras)))) {
                                                $line=102;
                                                $result="V5";
                                                if (true) break $try;
                                              }
                                              else {
                                                $line=103;
                                                if ($bool(($opEqualY(q,"V5")&&$opMembrY(\u03C3,$opUnionY(digitos,GCollections.asSet('_')))))) {
                                                  $line=103;
                                                  $result="V6";
                                                  if (true) break $try;
                                                }
                                                else {
                                                  $line=104;
                                                  if ($bool(($opEqualY(q,"V5")&&$opEqualY(\u03C3,',')))) {
                                                    $line=104;
                                                    $result="V7";
                                                    if (true) break $try;
                                                  }
                                                  else {
                                                    $line=105;
                                                    if ($bool(($opEqualY(q,"V5")&&$opEqualY(\u03C3,'$')))) {
                                                      $line=105;
                                                      $result="1A";
                                                      if (true) break $try;
                                                    }
                                                    else {
                                                      $line=106;
                                                      if ($bool(($opEqualY(q,"V6")&&$opMembrY(\u03C3,$opUnionY(digitos,letras))))) {
                                                        $line=106;
                                                        $result="V6";
                                                        if (true) break $try;
                                                      }
                                                      else {
                                                        $line=107;
                                                        if ($bool(($opEqualY(q,"V6")&&$opEqualY(\u03C3,',')))) {
                                                          $line=107;
                                                          $result="V7";
                                                          if (true) break $try;
                                                        }
                                                        else {
                                                          $line=108;
                                                          if ($bool(($opEqualY(q,"V6")&&$opEqualY(\u03C3,'$')))) {
                                                            $line=108;
                                                            $result="1A";
                                                            if (true) break $try;
                                                          }
                                                          else {
                                                            $line=109;
                                                            if ($bool(($opEqualY(q,"V7")&&$opMembrY(\u03C3,letras)))) {
                                                              $line=109;
                                                              $result="V5";
                                                              if (true) break $try;
                                                            }
                                                            else {
                                                              $line=110;
                                                              if ($bool(($opEqualY(q,"V7")&&$opEqualY(\u03C3,' ')))) {
                                                                $line=110;
                                                                $result="V4";
                                                                if (true) break $try;
                                                              }
                                                              else {
                                                                $line=111;
                                                                if ($bool(($opEqualY(q,"1A")&&$opEqualY(\u03C3,'B')))) {
                                                                  $line=111;
                                                                  $result="B0";
                                                                  if (true) break $try;
                                                                }
                                                                else {
                                                                  $line=118;
                                                                  if ($bool(($opEqualY(q,"B4")&&$opEqualY(\u03C3,'$')))) {
                                                                    $line=118;
                                                                    $result="2";
                                                                    if (true) break $try;
                                                                  }
                                                                  else {
                                                                    $line=121;
                                                                    if ($bool(($opEqualY(q,"2")&&$opEqualY(\u03C3,'a')))) {
                                                                      $line=121;
                                                                      $result="A0";
                                                                      if (true) break $try;
                                                                    }
                                                                    else {
                                                                      $line=122;
                                                                      if ($bool(($opEqualY(q,"A0")&&$opEqualY(\u03C3,'s')))) {
                                                                        $line=122;
                                                                        $result="A1";
                                                                        if (true) break $try;
                                                                      }
                                                                      else {
                                                                        $line=123;
                                                                        if ($bool(($opEqualY(q,"A1")&&$opEqualY(\u03C3,'s')))) {
                                                                          $line=123;
                                                                          $result="A2";
                                                                          if (true) break $try;
                                                                        }
                                                                        else {
                                                                          $line=124;
                                                                          if ($bool(($opEqualY(q,"A2")&&$opEqualY(\u03C3,'i')))) {
                                                                            $line=124;
                                                                            $result="A3";
                                                                            if (true) break $try;
                                                                          }
                                                                          else {
                                                                            $line=125;
                                                                            if ($bool(($opEqualY(q,"A3")&&$opEqualY(\u03C3,'g')))) {
                                                                              $line=125;
                                                                              $result="A4";
                                                                              if (true) break $try;
                                                                            }
                                                                            else {
                                                                              $line=126;
                                                                              if ($bool(($opEqualY(q,"A4")&&$opEqualY(\u03C3,'n')))) {
                                                                                $line=126;
                                                                                $result="A5";
                                                                                if (true) break $try;
                                                                              }
                                                                              else {
                                                                                $line=129;
                                                                                if ($bool(($opEqualY(q,"A5")&&$opEqualY(\u03C3,' ')))) {
                                                                                  $line=129;
                                                                                  $result="A6";
                                                                                  if (true) break $try;
                                                                                }
                                                                                else {
                                                                                  $line=130;
                                                                                  if ($bool(($opEqualY(q,"A5")&&$opEqualY(\u03C3,':')))) {
                                                                                    $line=130;
                                                                                    $result="A7";
                                                                                    if (true) break $try;
                                                                                  }
                                                                                  else {
                                                                                    $line=132;
                                                                                    if ($bool(($opEqualY(q,"A6")&&$opEqualY(\u03C3,':')))) {
                                                                                      $line=132;
                                                                                      $result="A7";
                                                                                      if (true) break $try;
                                                                                    }
                                                                                    else {
                                                                                      $line=134;
                                                                                      if ($bool(($opEqualY(q,"A7")&&$opEqualY(\u03C3,' ')))) {
                                                                                        $line=134;
                                                                                        $result="A8";
                                                                                        if (true) break $try;
                                                                                      }
                                                                                      else {
                                                                                        $line=135;
                                                                                        if ($bool(($opEqualY(q,"A7")&&$opMembrY(\u03C3,digitos)))) {
                                                                                          $line=135;
                                                                                          $result="A9";
                                                                                          if (true) break $try;
                                                                                        }
                                                                                        else {
                                                                                          $line=137;
                                                                                          if ($bool(($opEqualY(q,"A8")&&$opMembrY(\u03C3,digitos)))) {
                                                                                            $line=137;
                                                                                            $result="A9";
                                                                                            if (true) break $try;
                                                                                          }
                                                                                          else {
                                                                                            $line=139;
                                                                                            if ($bool(($opEqualY(q,"A9")&&$opMembrY(\u03C3,digitos)))) {
                                                                                              $line=139;
                                                                                              $result="A9";
                                                                                              if (true) break $try;
                                                                                            }
                                                                                            else {
                                                                                              $line=141;
                                                                                              if ($bool(($opEqualY(q,"A9")&&$opEqualY(\u03C3,' ')))) {
                                                                                                $line=141;
                                                                                                $result="A10";
                                                                                                if (true) break $try;
                                                                                              }
                                                                                              else {
                                                                                                $line=144;
                                                                                                if ($bool(($opEqualY(q,"A10")&&$opEqualY(\u03C3,'t')))) {
                                                                                                  $line=144;
                                                                                                  $result="A11";
                                                                                                  if (true) break $try;
                                                                                                }
                                                                                                else {
                                                                                                  $line=145;
                                                                                                  if ($bool(($opEqualY(q,"A11")&&$opEqualY(\u03C3,'o')))) {
                                                                                                    $line=145;
                                                                                                    $result="A12";
                                                                                                    if (true) break $try;
                                                                                                  }
                                                                                                  else {
                                                                                                    $line=148;
                                                                                                    if ($bool(($opEqualY(q,"A12")&&$opEqualY(\u03C3,' ')))) {
                                                                                                      $line=148;
                                                                                                      $result="A13";
                                                                                                      if (true) break $try;
                                                                                                    }
                                                                                                    else {
                                                                                                      $line=149;
                                                                                                      if ($bool(($opEqualY(q,"A12")&&$opEqualY(\u03C3,':')))) {
                                                                                                        $line=149;
                                                                                                        $result="A14";
                                                                                                        if (true) break $try;
                                                                                                      }
                                                                                                      else {
                                                                                                        $line=150;
                                                                                                        if ($bool(($opEqualY(q,"A13")&&$opEqualY(\u03C3,':')))) {
                                                                                                          $line=150;
                                                                                                          $result="A14";
                                                                                                          if (true) break $try;
                                                                                                        }
                                                                                                        else {
                                                                                                          $line=153;
                                                                                                          if ($bool(($opEqualY(q,"A14")&&$opEqualY(\u03C3,' ')))) {
                                                                                                            $line=153;
                                                                                                            $result="A15";
                                                                                                            if (true) break $try;
                                                                                                          }
                                                                                                          else {
                                                                                                            $line=154;
                                                                                                            if ($bool(($opEqualY(q,"A14")&&$opMembrY(\u03C3,letras)))) {
                                                                                                              $line=154;
                                                                                                              $result="A16";
                                                                                                              if (true) break $try;
                                                                                                            }
                                                                                                            else {
                                                                                                              $line=155;
                                                                                                              if ($bool(($opEqualY(q,"A15")&&$opMembrY(\u03C3,letras)))) {
                                                                                                                $line=155;
                                                                                                                $result="A16";
                                                                                                                if (true) break $try;
                                                                                                              }
                                                                                                              else {
                                                                                                                $line=158;
                                                                                                                if ($bool(($opEqualY(q,"A16")&&$opMembrY(\u03C3,letras)))) {
                                                                                                                  $line=158;
                                                                                                                  $result="A16";
                                                                                                                  if (true) break $try;
                                                                                                                }
                                                                                                                else {
                                                                                                                  $line=161;
                                                                                                                  if ($bool(($opEqualY(q,"A16")&&$opMembrY(\u03C3,digitos)))) {
                                                                                                                    $line=161;
                                                                                                                    $result="A17";
                                                                                                                    if (true) break $try;
                                                                                                                  }
                                                                                                                  else {
                                                                                                                    $line=162;
                                                                                                                    if ($bool(($opEqualY(q,"A16")&&$opEqualY(\u03C3,'_')))) {
                                                                                                                      $line=162;
                                                                                                                      $result="A17";
                                                                                                                      if (true) break $try;
                                                                                                                    }
                                                                                                                    else {
                                                                                                                      $line=165;
                                                                                                                      if ($bool(($opEqualY(q,"A17")&&$opMembrY(\u03C3,$opUnionY(digitos,letras))))) {
                                                                                                                        $line=165;
                                                                                                                        $result="A17";
                                                                                                                        if (true) break $try;
                                                                                                                      }
                                                                                                                      else {
                                                                                                                        $line=168;
                                                                                                                        if ($bool(($opEqualY(q,"A17")&&$opEqualY(\u03C3,'$')))) {
                                                                                                                          $line=168;
                                                                                                                          $result="2";
                                                                                                                          if (true) break $try;
                                                                                                                        }
                                                                                                                        else {
                                                                                                                          $line=174;
                                                                                                                          if ($bool(($opEqualY(q,"2")&&$opEqualY(\u03C3,'E')))) {
                                                                                                                            $line=174;
                                                                                                                            $result="E0";
                                                                                                                            if (true) break $try;
                                                                                                                          }
                                                                                                                          else {
                                                                                                                            $line=175;
                                                                                                                            if ($bool(($opEqualY(q,"E0")&&$opEqualY(\u03C3,'N')))) {
                                                                                                                              $line=175;
                                                                                                                              $result="E1";
                                                                                                                              if (true) break $try;
                                                                                                                            }
                                                                                                                            else {
                                                                                                                              $line=176;
                                                                                                                              if ($bool(($opEqualY(q,"E1")&&$opEqualY(\u03C3,'D')))) {
                                                                                                                                $line=176;
                                                                                                                                $result="E2";
                                                                                                                                if (true) break $try;
                                                                                                                              }
                                                                                                                              else {
                                                                                                                                $line=178;
                                                                                                                                $result="Err";
                                                                                                                                if (true) break $try;
                                                                                                                              }
                                                                                                                            }
                                                                                                                          }
                                                                                                                        }
                                                                                                                      }
                                                                                                                    }
                                                                                                                  }
                                                                                                                }
                                                                                                              }
                                                                                                            }
                                                                                                          }
                                                                                                        }
                                                                                                      }
                                                                                                    }
                                                                                                  }
                                                                                                }
                                                                                              }
                                                                                            }
                                                                                          }
                                                                                        }
                                                                                      }
                                                                                    }
                                                                                  }
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=180;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=185;
      String s=null;
      s=$defaultValue(String.class);
      $line=186;
      s=$cast(String.class,$fix(""));
      $line=188;
      if ($opEqualY(q,"B4")) {
        $line=188;
        $result=$opAdditY(s,"B");
        if (true) break $try;
      }
      else {
        $line=189;
        if ($opEqualY(q,"R7")) {
          $line=189;
          $result=$opAdditY(s,"R");
          if (true) break $try;
        }
        else {
          $line=190;
          if ($opEqualY(q,"V3")) {
            $line=190;
            $result=$opAdditY(s,"V");
            if (true) break $try;
          }
          else {
            $line=191;
            if ($opEqualY(q,"V4")) {
              $line=191;
              $result=$opAdditY(s,"v");
              if (true) break $try;
            }
            else {
              $line=192;
              if ($opEqualY(q,"A5")) {
                $line=192;
                $result=$opAdditY(s,"A(");
                if (true) break $try;
              }
              else {
                $line=193;
                if ($opEqualY(q,"A10")) {
                  $line=193;
                  $result=$opAdditY(s,"n");
                  if (true) break $try;
                }
                else {
                  $line=194;
                  if ($opEqualY(q,"A12")) {
                    $line=194;
                    $result=$opAdditY(s,"t");
                    if (true) break $try;
                  }
                  else {
                    $line=195;
                    if ($opEqualY(q,"A14")) {
                      $line=195;
                      $result=$opAdditY(s,"v)");
                      if (true) break $try;
                    }
                    else {
                      $line=196;
                      if ($opEqualY(q,"E2")) {
                        $line=196;
                        $result=$opAdditY(s,"E");
                        if (true) break $try;
                      }
                      else {
                        $line=197;
                        $result="";
                        if (true) break $try;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=200;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=204;
      $result="";
      if (true) break $try;
      $line=205;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"h",$line);
    }
    return $result;
  }
}
